trigger:
- master

pool:
 name: Default
 demands:
   - agent.name -equals ubuntu

steps:
- script: ls -al && pwd
  displayName: List Files & Cuurent Working Directory

- script: sudo apt update
  displayName: List Files

- script: sudo apt install -y openjdk-8-jdk
  displayName: INstalling Java

- script: sudo java -version
  displayName: Java Version

- script: ls -al && sudo bash ./build.sh && ls -al
  displayName: Create War file

- script: ls -al && mv ROOT.war ROOT$(Build.BuildNumber).war && ls -al
  displayName: Rename War file

- task: CopyFiles@2
  inputs:
    Contents: 'ROOT$(Build.BuildNumber).war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    Overwrite: true

- script: ls -al $(Build.ArtifactStagingDirectory)
  displayName: Moving to artifact folder and list artifacts

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ROOT$(Build.BuildNumber).war'
    publishLocation: Container

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(5141fc66-09b9-47e0-b096-e37c00de2a26)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name chikkiartifacts --account-key $(STORAGE_ACCOUNT_KEY) --pattern ROOT$(Build.BuildNumber).war -d buildartifacts -s /home/sagar/myagent/_work/1/a'

- task: Docker@2
  inputs:
    containerRegistry: 'chikkiACR'
    repository: 'azuredevops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(5141fc66-09b9-47e0-b096-e37c00de2a26)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az container create -g SRI1 --registry-username chikki --registry-password $(ACR_PWD) --name sridev-$(Build.BuildNumber) --image chikki.azurecr.io/azuredevops:$(Build.BuildNumber) --cpu 1 --memory 1 --ports 8080 --dns-name-label sridev-$(Build.BuildNumber) --location centralus  '